plugins {
    id 'java-library'
    id 'net.neoforged.moddev' version '2.0.134'
    id 'maven-publish'
}

version = project.mod_version
group = project.maven_group

base {
    archivesName = project.archives_base_name
}

repositories {
    mavenCentral()
}

neoForge {
    version = project.neo_version

    runs {
        server {
            server()
            gameDirectory = project.file('run/server')
        }
    }

    mods {
        client_locator {
            sourceSet sourceSets.main
        }
    }
}

processResources {
    def replaceProperties = [
            mod_version      : project.mod_version,
            minecraft_version: project.minecraft_version
    ]
    inputs.properties replaceProperties
    filesMatching('META-INF/neoforge.mods.toml') {
        expand replaceProperties
    }
}

tasks.withType(JavaCompile).configureEach {
    options.release = 21
    options.encoding = 'UTF-8'
}

java {
    withSourcesJar()
}

jar {
    from('LICENSE') {
        rename { "${it}_${project.archives_base_name}" }
    }
}
